### ISSUE TITLE
Understanding/Suggestions of/for the program

### ISSUE THREAD

**Issue by ghost** [arpancodes/Coffee-Machine#1]
Hello , This more of a question than a issue . So the thing is , for me , the code doesn't make sense ...atleast parts of it , as for each type of coffee it's a predefined amount of say ...coffee , milk , water , etc . So the part of the code where you ask for how much for each ingredient does not have to be there . Secondly , generally as far as I've seen , a coffee machine serves only one cup a time , so the number of cups also does not have to be there but if you want to , you can predefine the sizes of the cups like there can be options for small , medium  , etc with different prices for each size .  Then in the beginning itself , you can display the prices of each type of coffee along with the name . Then you ask the user to choose cup size ( Also displayed with price) , then the brewing process takes place and lastly for payment , print out the type of coffee (with the price) , the cup size ( with the price) and then the total . Then ( Not practical but since it's a general program) ask the user to input the amount he gave the machine and to either say "Insufficient funds" or calculate the change ( Change = total-pay) and print " You have to get (change) $/Rs  back , Have a great Day " . So yeah this is my suggestions

**Comment by arpancodes** [comment]
Hey! actually this project is a part of hyperskills curriculum 😄  They have set the stages which we have to pass and in each stage they give the specifications for the project so it is actually built according to their problem statement...

**Comment by ghost** [comment]
Ohhhh ok XD , Then yeah it's cool
